CREATE TABLE recipes (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    title VARCHAR (100) NOT NULL,
    image LONGTEXT NOT NULL,
    initialComment VARCHAR(280) NOT NULL,
    ingredients VARCHAR(1000) NOT NULL,
	elaboration LONGTEXT NOT NULL,
    finalQuote VARCHAR(45) NOT NULL
);

ALTER TABLE recipes ADD idFront VARCHAR (70) AFTER id;

INSERT INTO `freedb_cooking-recipes`.`recipes` (`idFront`, `title`, `image`, `initialComment`, `ingredients`, `elaboration`, `finalQuote`) VALUES ('1aas-9djf-as67-jhlt-89fh', 'Tiramisú', 'https://www.recetasnestle.com.ec/sites/default/files/srh_recipes/7f45d6f8807ebc775928651a3398dce9.png', 'Popular postre italiano que todo el mundo conoce. A nosotros nos gusta mucho, y además lo que no te comas lo puedes guardar en el congelador y sacarlo cuando lo necesites.', '6 huevos, 125 gr de azúcar, 500 gr de queso mascarpone, 300 gr de bizcochos de soletilla, 250 ml de café recién hecho, 50 ml de ron añejo (Si lo van a comer niños no echaremos el ron), Cacao en polvo', 'Hacemos el café, más bien cargado. Lo ponemos en un bol o plato y le añadimos el ron. Dejamos enfriar. Separamos las claras de las yemas y las ponemos en boles diferentes. Las claras las metemos en la nevera para que se mantengan frías, y las yemas las batimos junto con el azúcar, ayudados de unas varillas eléctricas, hasta que blanqueen y formen una crema amarilla clara. Le agregamos el mascarpone y volvemos a mezclar bien con las varillas hasta que quede una crema homogénea. Cogemos las claras de la nevera, añadimos una pizca de sal y las montamos bien a punto de nieve ayudados de nuevo por las varillas eléctricas. Tiene que quedar con una buena consistencia. Añadimos las claras, poco a poco, al bol de la crema del queso mascarpone, con movimientos envolventes y con suavidad para que no se bajen las claras montadas. Mezclamos bien hasta que quede una crema uniforme. Montamos el tiramisú: En un bol rectangular ponemos una capa de los bizcocho de soletilla mojados en el café, y con la parte que tiene el azúcar hacia abajo. Encima echamos una capa abundante de la crema preparada. Espolvoreamos cacao en polvo por encima. A continuación ponemos otra capa de bizcocho de soletilla empapado de la mezcla de café y ron. Encima otra capa generosa de la crema de queso mascarpone y terminamos espolvoreando una buena capa de cacao en polvo. Y listo… Si lo vamos a comer en unas horas mejor lo metemos al congelador para que se endurezca un poco. Y si no, lo ponemos en la parte más fría de la nevera. Yo siempre lo meto al congelador y lo saco un poco antes de comerlo porque nos gusta más bien helado.', '¡Que aproveche!');

INSERT INTO `freedb_cooking-recipes`.`recipes` (`idFront`, `title`, `image`, `initialComment`, `ingredients`, `elaboration`, `finalQuote`) VALUES ('1fgs-4dre-ads7-wert-98rt', 'Croquetas de pollo y ternera', 'https://2.bp.blogspot.com/-p8nPBXuooD8/UxTlzZmMJMI/AAAAAAAAAaY/ktasnV_l6Vg/s1600/Paso9.JPG', 'Para hacer esta receta, puedes utilizar el pollo y el morcillo que sobra del puchero o caldo de pollo.', 'Carne de pollo y morcillo que nos sobre de hacer caldo y que hemos picado muy finito con las tijeras,3 o 4 cucharadas de harina, 4 cucharadas de aceite, Media cebolla muy picadita, 1 litro de leche (yo la pongo semidesnatada), 1 pastilla de caldo de pollo tipo avecrem, Huevo, Pan rallado, Aceite para freírlas, Sal', 
        'En una sartén antiadherente ponemos a calentar el aceite y echamos a continuación la cebolla. Cuando esté transparente añadimos la harina. Lo rehogamos y añadimos poco a poco la leche (sin dejar de remover). Cuando hayamos puesto la mitad de la leche le ponemos la carne y removemos. Añadimos la pastilla de Avecrem, seguimos añadiendo la leche y removiendo hasta que la masa se despegue de la sartén. Cuando la masa esté lista la extendemos en una bandeja de cristal y la dejamos enfriar (para que no se forme una capa dura al enfriarse yo le pongo inmediatamente film transparente bien pegadito a la masa). Luego las liamos y las pasamos por huevo y pan rallado. Se fríen en abundante aceite caliente y se dejan escurrir en papel de cocina para que suelten el aceite sobrante. Las pasamos a una bandeja y ¡listo!" NOTA: como salen bastantes croquetas, podemos reservar en una bandeja de poliespan unas cuantas (ya con el pan rallado) y congelarlas, envueltas en film transparente.', '¡Que aproveche!');
        
UPDATE `freedb_cooking-recipes`.`recipes` SET `ingredients` = '6 huevos,125 gr de azúcar,500 gr de queso mascarpone,300 gr de bizcochos de soletilla, 250 ml de café recién hecho, 50 ml de ron añejo (Si lo van a comer niños no echaremos el ron),Cacao en polvo', `elaboration` = 'Hacemos el café, más bien cargado.Lo ponemos en un bol o plato y le añadimos el ron.Dejamos enfriar.Separamos las claras de las yemas y las ponemos en boles diferentes.Las claras las metemos en la nevera para que se mantengan frías, y las yemas las batimos junto con el azúcar, ayudados de unas varillas eléctricas, hasta que blanqueen y formen una crema amarilla clara.Le agregamos el mascarpone y volvemos a mezclar bien con las varillas hasta que quede una crema homogénea.Cogemos las claras de la nevera, añadimos una pizca de sal y las montamos bien a punto de nieve ayudados de nuevo por las varillas eléctricas.Tiene que quedar con una buena consistencia.Añadimos las claras, poco a poco, al bol de la crema del queso mascarpone, con movimientos envolventes y con suavidad para que no se bajen las claras montadas.Mezclamos bien hasta que quede una crema uniforme.Montamos el tiramisú: En un bol rectangular ponemos una capa de los bizcocho de soletilla mojados en el café, y con la parte que tiene el azúcar hacia abajo.Encima echamos una capa abundante de la crema preparada.Espolvoreamos cacao en polvo por encima.A continuación ponemos otra capa de bizcocho de soletilla empapado de la mezcla de café y ron.Encima otra capa generosa de la crema de queso mascarpone y terminamos espolvoreando una buena capa de cacao en polvo.Y listo…Si lo vamos a comer en unas horas mejor lo metemos al congelador para que se endurezca un poco. Y si no, lo ponemos en la parte más fría de la nevera. Yo siempre lo meto al congelador y lo saco un poco antes de comerlo porque nos gusta más bien helado.' WHERE (`id` = '1');

